---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:antonputra/lesson-158-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACASUbJVlJV/mYQk7tbQKPT2LlNK3/wuBU/kjv7niH0scwAAAKCLk/sni5P7
    JwAAAAtzc2gtZWQyNTUxOQAAACASUbJVlJV/mYQk7tbQKPT2LlNK3/wuBU/kjv7niH0scw
    AAAEDvzahZAzV3wUOde2ktuai9cF3iI3yWqprnNnkXuqIZ5hJRslWUlX+ZhCTu1tAo9PYu
    U0rf/C4FT+SO/ueIfSxzAAAAGWhhbGlsLmFrc3UuMUBjb3Rpdml0aS5jb20BAgME
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
